In [45]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\mohammad asad\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mohammad asad\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mohammad asad\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mohammad asad\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mohammad asad\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\mohammad asad\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: C:\Users\Mohammad Asad\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [1]:
import numpy as np
import pandas as pd

In [12]:
df=pd.read_csv("airline_logical_data.csv")

In [48]:
df.describe()

,Flight_Number,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Delay_minutes,Passenger_Count
count,103000.000000,99923.000000,98884.000000,97864.000000,99919.000000,100939.000000,103000.000000
mean,5504.013641,917.581698,1.723958,3404.123384,3333.542792,21.387516,142.368816
std,2600.725983,570.654171,0.836503,664.495556,1993.218002,19.882704,71.012163
min,1000.000000,0.000000,0.500000,1715.010897,500.000000,0.000000,29.000000
25%,3250.000000,499.000000,1.081441,2897.401610,1768.671832,4.593466,96.000000
50%,5510.500000,907.000000,1.690917,3322.931316,3291.577734,17.575390,136.000000
75%,7752.000000,1384.000000,2.278145,3870.952712,4924.585924,32.179635,174.000000
max,9998.000000,1769.000000,4.349843,5612.914951,7575.644450,125.612276,332.000000

In [51]:
df.head() #bydefault it will show 5 but we can change the values

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count
0,8498,SpiceJet,ATR72,CCU,MAA,2023-06-12,1384.0,3.094867,2963.516704,3828.490167,Cloudy,0.000000,62
1,5263,IndiGo,A320,AMD,PNQ,2023-09-21,519.0,NaN,2912.486246,1790.502002,Cloudy,27.908655,119
2,1877,GoAir,B737,CCU,DEL,2023-11-30,1423.0,2.112585,2177.869901,5122.704201,Cloudy,26.339672,122
3,1598,GoAir,B737,AMD,HYD,2023-06-30,907.0,1.515557,2204.381503,3289.369504,Cloudy,13.771963,143
4,2722,GoAir,ATR72,HYD,PNQ,2023-10-24,529.0,1.717573,2321.112931,1543.099700,Clear,18.920403,40

In [52]:
df.tail() #will give last 5 values by default

,Flight_Number,Airline,Aircraft_Type,Origin,Destination,Date,Distance_km,Duration_hours,Ticket_Price,Fuel_Cost,Weather_Condition,Delay_minutes,Passenger_Count
102995,2098,GoAir,A321,CCU,AMD,2023-12-06,1753.0,2.531112,2995.180173,6435.115093,Clear,7.730974,195
102996,1978,GoAir,A321,AMD,PNQ,2023-07-21,519.0,1.137145,2971.397586,2030.405612,Clear,3.564183,158
102997,7474,Air India,A320,DEL,DEL,2023-08-29,0.0,0.500000,3380.840213,500.000000,Clear,0.000000,93
102998,2248,IndiGo,B777,MAA,PNQ,2023-07-17,933.0,1.425115,3542.425616,3908.780885,Rainy,27.970932,243
102999,6529,SpiceJet,ATR72,BOM,MAA,2023-05-23,1056.0,2.655092,2963.984721,2977.489964,Foggy,88.251829,65

In [56]:
df.dtypes

Flight_Number          int64
Airline               object
Aircraft_Type         object
Origin                object
Destination           object
Date                  object
Distance_km          float64
Duration_hours       float64
Ticket_Price         float64
Fuel_Cost            float64
Weather_Condition     object
Delay_minutes        float64
Passenger_Count        int64
dtype: object

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103000 entries, 0 to 102999
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Flight_Number      103000 non-null  int64
 1   Airline            103000 non-null  object
 2   Aircraft_Type      103000 non-null  object
 3   Origin             103000 non-null  object
 4   Destination        103000 non-null  object
 5   Date               103000 non-null  object
 6   Distance_km        99923 non-null   float64
 7   Duration_hours     98884 non-null   float64
 8   Ticket_Price       97864 non-null   float64
 9   Fuel_Cost          99919 non-null   float64
 10  Weather_Condition  103000 non-null  object
 11  Delay_minutes      100939 non-null  float64
 12  Passenger_Count    103000 non-null  int64
dtypes: float64(5), int64(2), object(6)
memory usage: 10.2+ MB

In [11]:
df.isna().sum()

Flight_Number           0
Airline                 0
Aircraft_Type           0
Origin                  0
Destination             0
Date                    0
Distance_km          3000
Duration_hours       4000
Ticket_Price         5000
Fuel_Cost            3000
Weather_Condition       0
Delay_minutes        2000
Passenger_Count         0
dtype: int64

In [3]:
df.isna().sum()/len(df)*100

Flight_Number        0.000000
Airline              0.000000
Aircraft_Type        0.000000
Origin               0.000000
Destination          0.000000
Date                 0.000000
Distance_km          2.987379
Duration_hours       3.996117
Ticket_Price         4.986408
Fuel_Cost            2.991262
Weather_Condition    0.000000
Delay_minutes        2.000971
Passenger_Count      0.000000
dtype: float64

In [15]:
df.duplicated().sum()

np.int64(3000)

In [18]:
a = df[df.duplicated()]
a.to_csv("duplicates.csv",index=False) 
df.drop_duplicates(inplace=True)

In [28]:
df[(df["Origin"]=='AMD') & (df["Destination"]=="HYD")]["Distance_km"].unique()

array([907.])

filling all distance null values.

In [34]:
li=df[df["Distance_km"].notna()]["Distance_km"].unique().tolist()  
#li

In [21]:
li=df[df["Distance_km"].notna()]["Distance_km"].unique().tolist()  
#here we are taking all the unique values .
li.remove(0.0)
#now we removed 0.0 also

df.loc[(df["Origin"]==df["Destination"]) & (df["Distance_km"].isna()),"Distance_km"]=0.0
#here we filled the 0.0 values in place of null where destination and origin is same.
#which means the flight has not taken off

#odd is origin destination distance
odd={i: [df[df["Distance_km"]==i] ["Origin"].unique().tolist(), # we are taking unique list of origin
        df[df["Distance_km"]==i]["Destination"].unique().tolist()] #we are taking unique list of destination
        for i in li}
for i,j in odd.items():
    df.loc[(df["Origin"]!=df["Destination"]) &
            (df["Origin"].isin(j[0])) &   #i is iterating in li and j is iterating in origin 
            (df["Destination"].isin(j[1])) &    # and destination
            (df["Distance_km"].isna()),"Distance_km"]=i
#after  the completion of condition we closed the condition with (,) then we made a change in all 
#distance where destination and origin's values are null and filled it.

In [43]:
df.isna().sum()

Flight_Number           0
Airline                 0
Aircraft_Type           0
Origin                  0
Destination             0
Date                    0
Distance_km             0
Duration_hours       4116
Ticket_Price         5136
Fuel_Cost            3081
Weather_Condition       0
Delay_minutes        2061
Passenger_Count         0
dtype: int64

In [85]:
df["Aircraft_Type"].unique()

array(['ATR72', 'A320', 'B737', 'A321', 'B777'], dtype=object)

In [8]:

main={i: {k: {q: df[(df["Aircraft_Type"]== i) &
                    (df["Distance_km"]== k) &
                    (df["Weather_Condition"]== q)]["Fuel_Cost"].mean()
            for q in df[(df["Aircraft_Type"] == i) & (df["Distance_km"]== k)]["Weather_Condition"].unique()
        }
        for k in df[df["Aircraft_Type"] == i]["Distance_km"].unique()
    }
    for i in df["Aircraft_Type"].unique()
}
for i,j in main.items():
    for m,n in j.items():
        for q,w in n.items():
            df.loc[(df["Aircraft_Type"]==i) &
            (df["Distance_km"] == m) &
            (df["Weather_Condition"] == q)  &
            (df["Fuel_Cost"].isna()),"Fuel_Cost"]=w

In [9]:
df.isna().sum()

Flight_Number           0
Airline                 0
Aircraft_Type           0
Origin                  0
Destination             0
Date                    0
Distance_km             0
Duration_hours       4000
Ticket_Price         5000
Fuel_Cost               0
Weather_Condition       0
Delay_minutes        2000
Passenger_Count         0
dtype: int64

In [ ]:
# ----------------Filling Ticket price-------------------------------

In [11]:
#AADT=airline aircraft type distance ticket price
AADT={i:{m:{q: df[(df["Airline"]==i) &
                  (df["Aircraft_Type"]==m) &
                  (df["Distance_km"]==q) &
                  (df["Ticket_Price"].notna())]["Ticket_Price"].mean() for q in n
                }
                    for m,n in {k:df[(df["Airline"]==i) &
                                  (df["Aircraft_Type"]==k) &
                                  (df["Distance_km"]!=0.0)]["Distance_km"].unique().tolist() for k in j}.items()
            }
                                for i,j in {i:df[df["Airline"]==i]["Aircraft_Type"].unique().tolist()
                                           for i in df["Airline"].unique().tolist()
                                           }.items()
        }
for i,j in AADT.items():
    for m,n in j.items():
        for q,w in n.items():
            df.loc[(df["Airline"]==i) &
                   (df["Aircraft_Type"]==m) &
                   (df["Distance_km"]==q) &
                   (df["Ticket_Price"].isna()),"Ticket_Price"]=w

In [12]:
df.isna().sum()

Flight_Number           0
Airline                 0
Aircraft_Type           0
Origin                  0
Destination             0
Date                    0
Distance_km          3000
Duration_hours       4000
Ticket_Price          145
Fuel_Cost            3000
Weather_Condition       0
Delay_minutes        2000
Passenger_Count         0
dtype: int64

In [15]:
#ADWD=aircraft distance weather conditon duration hours
ADWD = {i:
        {q:
         {l:
        df[(df["Aircraft_Type"]==i) &
          (df["Distance_km"]==q) &
          (df["Weather_Condition"]==l) &
          (df["Duration_hours"].notna())]["Duration_hours"].mean() for l in w
            } for q,w in {k: df["Weather_Condition"].unique().tolist() for k in j}.items()

            }for i,j in {i:df[df["Aircraft_Type"]==i]["Distance_km"].unique().tolist()
                for i in df["Aircraft_Type"].unique().tolist()}.items()
            }

for i,j in ADWD.items():
    for k,l in j.items():
        for m,n in l.items():
            df.loc[(df["Aircraft_Type"]==i) &
                   (df["Distance_km"]==k) &
                   (df["Weather_Condition"]==m) &
                   (df["Duration_hours"].isna()),"Duration_hours"]=n

In [ ]:
#ADWD=aircraft distance weather conditon duration hours
#in this we have done this with random so it will place a random value in place of null value.
ADWD = {i:
        {q:
         {l:
        df[(df["Aircraft_Type"]==i) &
          (df["Distance_km"]==q) &
          (df["Weather_Condition"]==l) &
          (df["Duration_hours"].notna())]["Duration_hours"].unique().tolist() for l in w
            } for q,w in {k: df["Weather_Condition"].unique().tolist() for k in j}.items()

            }for i,j in {i:df[df["Aircraft_Type"]==i]["Distance_km"].unique().tolist()
                for i in df["Aircraft_Type"].unique().tolist()}.items()
            }

for i,j in ADWD.items():
    for k,l in j.items():
        for m,n in l.items():
            df.loc[(df["Aircraft_Type"]==i) &
                   (df["Distance_km"]==k) &
                   (df["Weather_Condition"]==m) &
                   (df["Duration_hours"].isna()),"Duration_hours"]=np.random.choice(n)

In [16]:
df.isna().sum()

Flight_Number           0
Airline                 0
Aircraft_Type           0
Origin                  0
Destination             0
Date                    0
Distance_km             0
Duration_hours          0
Ticket_Price          675
Fuel_Cost               0
Weather_Condition       0
Delay_minutes        2000
Passenger_Count         0
dtype: int64

In [ ]:
 #filling 675 values in ticket price

In [4]:
#ticket price
AODT={i:{m:{q:df[(df["Aircraft_Type"]==i)&
                  (df["Origin"]==m)&
                  (df["Destination"]==q)&
                  (df["Ticket_Price"].notna())]["Ticket_Price"].mean()
                   for q in n  
                } for m,n in
                {k:
                 df[(df["Aircraft_Type"]==i)&
                            (df["Origin"]==k)]["Destination"].unique().tolist()
                            for k in j 
                }.items()
        }
        for i,j in {i:
                    df[df["Aircraft_Type"]==i]["Origin"].unique().tolist()
                        for i in df["Aircraft_Type"].unique().tolist()
                        }.items()
            }
#AODT

In [ ]:
while int(df["Ticket_Price"].isna().sum())!=0:
    for i,j in AODT.items():
        for k,l in j.items():
            for m,n in l.items():
                des=np.random.choice(df[(df["Aircraft_Type"]==i)&
                                        (df["Origin"]==k)&
                                           (df["Distance_km"]!=0)]["Destination"].unique().tolist())
                if des==m:
                    df.loc[(df["Aircraft_Type"]==i)&
                           (df["Origin"]==k)&
                                (df["Ticket_Price"].isna()),"Ticket_Price"]=n

In [16]:
df.isna().sum()

Flight_Number           0
Airline                 0
Aircraft_Type           0
Origin                  0
Destination             0
Date                    0
Distance_km          3000
Duration_hours       4000
Ticket_Price          145
Fuel_Cost            3000
Weather_Condition       0
Delay_minutes        2000
Passenger_Count         0
dtype: int64

In [ ]:
def ap_di(n):
    return np.round(n/100)

WD={'Clear':[0,3],"Cloudy":[3,5],"Rainy":[5,8],"Foggy":[8,10]}

In [ ]:
def ap_di(n):
    return np.round(n/100)

WD={'Clear':[0,3],"Cloudy":[3,5],"Rainy":[5,8],"Foggy":[8,10]}

AAWD={i:{l:{p:[[a,ap_di(a)]for a in o]for p,o in{q:df[(df["Airline"]==i)&
            (df["Aircraft_Type"]==l)&
            (df["Weather_Condition"]==q)]["Distance_km"].unique().tolist()
            for q in m}.items()}
                for l,m in{k:df[(df["Airline"]==i) &
                (df["Aircraft_Type"]==k)]["Weather_Condition"].unique().tolist()
                for k in j}.items()}
                    for i,j in{i:df[df["Airline"]==i]["Aircraft_Type"].unique().tolist()
                        for i in df["Airline"].unique().tolist()}.items()}

EV=[]
for w,b in WD.items():
    for i,j in AAWD.items():
        for k,l in j.items():
            for m,n in l.items():
                for d in n:
                    #print(i,k,m,d,w,b)
                    try:
                        if m=='Clear' and w=="Clear":
                            df.loc[(df["Airline"]==i) &
                                (df["Aircraft_Type"]==k) &
                                (df["Distance_km"]==d[0]) &
                                (df["Weather_Condition"]==m)&
                                (df["Delay_minutes"].isna()),
                                "Delay_minutes"]=np.random.choice(df[(df["Aircraft_Type"]==k)&
                                                                    (df["Distance_km"]==d[0]) &
                                                                    (df["Weather_Condition"]==m)&
                                                                    (df["Delay_minutes"].notna())&
                                                                    (df["Delay_minutes"]>=0) &
                                                                    (df["Delay_minutes"]<=d[1]+np.random.randint(b[0],b[1]+1))]
                                                                    ["Delay_minutes"].unique().tolist()) 

                        elif m=='Cloudy' and w=="Cloudy":
                            df.loc[(df["Airline"]==i) &
                                (df["Aircraft_Type"]==k) &
                                (df["Distance_km"]==d[0]) &
                                (df["Weather_Condition"]==m)&
                                (df["Delay_minutes"].isna()),
                                "Delay_minutes"]=np.random.choice(df[(df["Aircraft_Type"]==k)&
                                                                    (df["Distance_km"]==d[0]) &
                                                                    (df["Weather_Condition"]==m)&
                                                                    (df["Delay_minutes"].notna())&
                                                                    (df["Delay_minutes"]>=0 +np.random.randint(b[0],b[1]+1)) &
                                                                    (df["Delay_minutes"]<=d[1]+np.random.randint(b[0],b[1]+1))]
                                                                    ["Delay_minutes"].unique().tolist()) 
            
                        elif m=='Rainy' and w=="Rainy":
                            df.loc[(df["Airline"]==i) &
                                (df["Aircraft_Type"]==k) &
                                (df["Distance_km"]==d[0]) &
                                (df["Weather_Condition"]==m)&
                                (df["Delay_minutes"].isna()),
                                "Delay_minutes"]=np.random.choice(df[(df["Aircraft_Type"]==k)&
                                                                    (df["Distance_km"]==d[0]) &
                                                                    (df["Weather_Condition"]==m)&
                                                                    (df["Delay_minutes"].notna())&
                                                                    (df["Delay_minutes"]>=d[1]+(np.random.randint(b[0],b[1]+1)/2)) &
                                                                    (df["Delay_minutes"]<=d[1]+np.random.randint(b[0],b[1]+1))]
                                                                    ["Delay_minutes"].unique().tolist()) 

                        elif m=='Foggy' and w=="Foggy":
                            df.loc[(df["Airline"]==i) &
                                (df["Aircraft_Type"]==k) &
                                (df["Distance_km"]==d[0]) &
                                (df["Weather_Condition"]==m)&
                                (df["Delay_minutes"].isna()),
                                "Delay_minutes"]=np.random.choice(df[(df["Aircraft_Type"]==k)&
                                                                    (df["Distance_km"]==d[0]) &
                                                                    (df["Weather_Condition"]==m)&
                                                                    (df["Delay_minutes"].notna())]
                                                                    ["Delay_minutes"].unique().tolist()) 

                    except Exception as e:
                        EV.append([i,k,m,d,w,b])

In [ ]:
df.isna().sum()

Flight_Number        0
Airline              0
Aircraft_Type        0
Origin               0
Destination          0
Date                 0
Distance_km          0
Duration_hours       0
Ticket_Price         0
Fuel_Cost            0
Weather_Condition    0
Delay_minutes        0
Passenger_Count      0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
def hms(a):
    h=int(a)
    m=int((a-h)*60)
    s=round((((a-h)*60)-m)*60)
    if s>=60:
        if s==60:
            s=0
        else:
            s=s-60
        m+=1
    if m>=60:
        if m==60:
            m=0
        else:
            m=m-60
        h+=1
    return (f"{h:02d}:{m:02d}:{s:02d}")
df["Duration_hours"]=df["Duration_hours"].apply(lambda x:hms(x))

In [ ]:
def dm(n):
    h=0
    m=int(n)
    s=round((n-int(n))*60)
    while m>=60:
        if m==60:
            m=0
        else:
            m=m-60
        h+=1
    while s>=60:
        if s==60:
            s=0
        else:
            s=s-60
        m+=1
    return (f"{h:02d}:{m:02d}:{s:02d}")
df["Delay_minutes"]=df["Delay_minutes"].apply(lambda x:dm(x))

In [ ]:
df.isna().sum()

Flight_Number        0
Airline              0
Aircraft_Type        0
Origin               0
Destination          0
Date                 0
Distance_km          0
Duration_hours       0
Ticket_Price         0
Fuel_Cost            0
Weather_Condition    0
Delay_minutes        0
Passenger_Count      0
dtype: int64

In [ ]:
# df.to_csv("Cleaned_Data.csv",index=False)